name: learning-pytorch
root: /home/quinten/Documents/Software_Development/learning-pytorch/

on_project_start: echo -ne "\033]0;learning-pytorch\007"

windows:
  - editor:
      layout: main-vertical
      panes:
      - code:
        - source .venv/bin/activate
        - nv .
  - terminal:
      layout: even-horizontal
      panes:
      - terminal:
        - source .venv/bin/activate
